# Generated by Django 5.0.3 on 2024-04-15 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_blocked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_blocked",
        ),
    ]
