# Generated by Django 5.0.3 on 2024-03-08 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50, verbose_name="Имя")),
                ("lastname", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "middlename",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Клиент сервиса",
                "verbose_name_plural": "Клиенты сервиса",
                "ordering": ("lastname", "firstname"),
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Время начала рассылки")),
                ("end_time", models.TimeField(verbose_name="Время окончания рассылки")),
                (
                    "request_period",
                    models.CharField(
                        choices=[
                            ("Ежедневно", "Ежедневно"),
                            ("Еженедельно", "Еженедельно"),
                            ("Ежемесячно", "Ежемесячно"),
                        ],
                        max_length=50,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создана", "Создана"),
                            ("Запущена", "Запущена"),
                            ("Завершена", "Завершена"),
                        ],
                        default="Создана",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        to="mailing.client", verbose_name="Клиенты рассылки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Почтовая рассылка",
                "verbose_name_plural": "Почтовые рассылки",
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_try",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время последней попытки"
                    ),
                ),
                ("status", models.BooleanField(verbose_name="Статус попытки")),
                (
                    "mail_service_response",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Ответ почтового сервиса",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.client",
                        verbose_name="Клиент сервиса",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="Почтовая рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог",
                "verbose_name_plural": "Логи",
            },
        ),
        migrations.CreateModel(
            name="Massage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=150, verbose_name="Тема письма"),
                ),
                ("body", models.TextField(verbose_name="Тело письма")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="Почтовая рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение для рассылки",
                "verbose_name_plural": "Сообщения для рассылок",
            },
        ),
    ]
