# Generated by Django 5.0.3 on 2024-04-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="client",
        ),
        migrations.AddField(
            model_name="mailing",
            name="last_mailing",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время последней рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания рассылки"
            ),
        ),
    ]
