# Generated by Django 5.0.3 on 2024-04-14 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0002_remove_log_client_mailing_last_mailing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="massage",
            name="mailing",
        ),
        migrations.AddField(
            model_name="mailing",
            name="massage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.massage",
                verbose_name="Сообщение для рассылки",
            ),
            preserve_default=False,
        ),
    ]
