# Generated by Django 5.0.3 on 2024-04-15 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0004_client_owner_mailing_owner_massage_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("is_active", "Активация рассылки")],
                "verbose_name": "Почтовая рассылка",
                "verbose_name_plural": "Почтовые рассылки",
            },
        ),
    ]
