# Generated by Django 5.0.3 on 2024-04-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0006_mailing_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="next_mailing",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время следующей рассылки"
            ),
        ),
    ]
