# Generated by Django 5.0.3 on 2024-04-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0007_mailing_next_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="last_mailing",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата и время последней рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="next_mailing",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата и время следующей рассылки"
            ),
        ),
    ]
